# Generated by Django 5.0.1 on 2024-01-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mpapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyplant',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
